language: objective-c
xcode_project: ZHLocalizationStringManger/ZHLocalizationStringManger.xcodeproj
xcode_scheme: ZHLocalizationStringManger
xcodebuild -project ZHLocalizationStringManger.xcodeproj -target ZHLocalizationStringManger -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
